edition = "2021"
max_width = 100
use_small_heuristics = "Default"
indent_style = "Block"
use_field_init_shorthand = true
format_code_in_doc_comments = true
normalize_comments = true
wrap_comments = true
